### ISSUE TITLE
Analytics API endpoint

### ISSUE THREAD

**Issue by stefanjudis** [buttondown-email/roadmap#910] opened 2022-10-30 08:57 UTC
Heyooo. 👋

I'm looking into a sponsorship section for web weekly, and I'd love to include an always fresh an analytics section.

Is there a chance to open up the analytics endpoint? 🫣

Note: it's very low prio though. :)

**Comment by jmduke** [comment] 2022-10-30 13:02
Closing this as a dupe of #565 — let’s chat over there!

**Closed by jmduke** 2022-10-30 13:02 UTC
Labels: feature
