### ISSUE TITLE
Filter by "not tag"

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#2103] opened 2023-11-27 12:32 UTC
Currently you can filter by tags on the Subscribers view, this would be adding another state where it’s filtered by _not_ that tag. 

(This could get a bit intuitively tricky because currently the tags are OR’d together but OR-ing a NOT "tag" _may or may not be_ what one would expect?)

https://secure.helpscout.net/conversation/2432266550/1948

**Comment by jmduke** [comment] 2023-11-28 17:49
Closing as dupe of https://github.com/buttondown-email/roadmap/issues/884.

**Closed by jmduke** 2023-11-28 17:49 UTC
Labels: ergonomics
