### ISSUE TITLE
Email sending progress bar shows 100% but count does not

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1645] opened 2023-07-07 12:48 UTC
Example: 

![](https://github.com/buttondown-email/roadmap/assets/30215449/ff8356e0-14e6-42aa-bad7-a4d82384cc81)

https://secure.helpscout.net/conversation/2294835034/1084

**Comment by jmduke** [comment] 2023-11-21 22:48
Dupe of https://github.com/buttondown-email/roadmap/issues/1474

**Closed by jmduke** 2023-11-21 22:48 UTC
Labels: bug
