### ISSUE TITLE
Twitter embeds are dark-on-dark in macOS Mail dark mode

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#1725] opened 2023-07-24 13:01 UTC
<img width="509" alt="2023-07-24 at 09 00 36@2x" src="https://github.com/buttondown-email/roadmap/assets/30215449/efab7b28-99d6-4648-9d3d-77e2553700e1">

https://secure.helpscout.net/conversation/2308307468/1136

**Comment by jmduke** [comment] 2023-10-19 19:57
Closing as dupe of https://github.com/buttondown-email/roadmap/issues/1053.

**Closed by jmduke** 2023-10-19 19:57 UTC
Labels: bug
