### ISSUE TITLE
The subscriber list should display every subscribers by default

### ISSUE THREAD

**Issue by RoneoOrg** [buttondown-email/roadmap#415] opened 2022-01-12 00:28 UTC
Hi there,

once subscribed to Buttondown, I registered a bunch of personal emails and checked the result on the [subscriber page](https://buttondown.email/subscribers?order=-creation_date&filter=&page=1).

Surprisingly, no single subscriber appeared there, and I lost a bit of time debugging my code.

In fact, only ***confirmed*** subscribers are displayed by default, but the UI tends to tell something like
- we are displaying every subscribers 
- click on the 'Confirmed subscribers' ***to filter*** this list

The misleading button is emphasized in the following screenshot:

![buttondown-ui](https://user-images.githubusercontent.com/77257518/149042051-ce9a7be9-34d2-4b38-b47b-58eb794bd728.png)

**Comment by jmduke** [comment] 2022-01-12 21:55
Agreed. Closing as a dupe of https://github.com/buttondown-email/roadmap/issues/296.

**Closed by jmduke** 2022-01-12 21:55 UTC
