### ISSUE TITLE
stale analytics never update, systematically undercounting opens

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#2366] opened 2024-01-28 04:58 UTC
After the opens/open-rate analytics stats first show up (I don't know exactly when that happens... about one day post-publish, maybe a little less?), on any given email/issue, AFAIK those numbers never change ever again.

This incorrectness seems like a defect, because people keep opening emails (sure, it drops off quickly) and those numbers quickly become wrong and stay that way. This hides any long tail of opens, and it also matters more for small newsletters where every subscriber is a known human and you actually care about whether they've seen the information or not. For me I notice it also creates some false appearance of variation in my open rates when in fact it's sometimes more due (my conjecture after laboriously comparing some line-counts-of-opens) to the pattern of when people open their emails across days-of-the-week.

I believe this is the case because, when in the Analytics modal I expand the list of opens, there are consistently more rows/names there than the displayed total says there should be. And it's not just #2115 - yeah it's very obvious on the "direct to archive, then send to individuals" emails, but this happens on every email AFAICT.

**Comment by jmduke** [comment] 2024-01-29 14:40
Closing as a dupe of (much more poorly named) https://github.com/buttondown-email/roadmap/issues/1847! (Will bump this up to this week.)

**Closed** 2024-01-29 16:39 UTC
