### ISSUE TITLE
It's possible for sending progress bar to be 100% but 0 emails sent

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#2188] opened 2023-12-20 14:17 UTC
![](https://github.com/buttondown-email/roadmap/assets/30215449/e9574609-2892-4fe8-a330-295be0fa77ed)

https://secure.helpscout.net/conversation/2458024940/2157

**Comment by jmduke** [comment] 2023-12-30 20:36
Closing as dupe of https://github.com/buttondown-email/roadmap/issues/1645.

**Closed by jmduke** 2023-12-30 20:36 UTC
Labels: bug
